import { test } from 'node:test';
import { cpSync, writeFileSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { ROOT } from '../src/config.ts';
import { renderReadme } from '../src/readme.ts';
import { sandbox } from './fixture.ts';

/// Renders the README against examples/ and writes the result to examples/README.md, so the
/// repository shows what a synced mirror looks like before it has ever synced.
test('examples readme', { skip: process.env.GENERATE_EXAMPLES !== '1' }, () => {
  const { root, cleanup } = sandbox();
  try {
    for (const name of ['live', 'infections', 'mutations', 'transmissions']) {
      cpSync(join(ROOT, 'examples', name), join(root, name), { recursive: true });
    }
    writeFileSync(join(root, 'README.md'), readFileSync(join(ROOT, 'README.md'), 'utf8'));
    renderReadme(root);
    const rendered = readFileSync(join(root, 'README.md'), 'utf8')
      .replace('![VIRAL](viralban.png)', '![VIRAL](../viralban.png)')
      .replace(/\]\((live|infections|mutations|transmissions)\//g, '](../$1/');
    writeFileSync(join(ROOT, 'examples/README.md'),
      '<!-- Generated by `GENERATE_EXAMPLES=1 npm test`. A preview of a synced mirror. -->\n\n'
      + rendered);
  } finally { cleanup(); }
});
